// example/tic-tac-toe/angular/tic-tac-toe/src/app/game-info/game-info.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-game-info',
  templateUrl: './game-info.component.html',
  styleUrls: ['./game-info.component.css']
})
export class GameInfoComponent implements OnInit {
  @Input() next: string;
  @Input() moves: Array<string>;
  @Output() onJump = new EventEmitter<number>();

  constructor() { }

  ngOnInit() {
  }

  jump(move) {
    this.onJump.emit(move);
  }
}

<div class="game-info">
    <div>Next player: {{ next }}</div>
    <div class="history-buttons">
        <li *ngFor="let desc of moves; index as move">
            <button (click)="jump(move)">{{ desc }}</button>
        </li>
    </div>
</div>

// example/tic-tac-toe/vue/tic-tac-toe/src/components/GameInfo.vue
<template>
    <div class="game-info">
        <div>{{ status }}</div>
        <div class="history-buttons">
            <li v-for="(move, index) in moves" :key="index">
                <button @click="onJump(index)">{{ move }}</button>
            </li>
        </div>
    </div>
</template>

<script>
export default {
    name: 'GameInfo',
    props: {
      status: String,
      moves: Array,
      onJump: Function,
    },
}
</script>

<style scoped>
li {
    list-style-type: none;
}
</style>
